version: '3.3'
services:
    alist:
        restart: always
        volumes:
            - '/etc/alist:/opt/alist/data'
        ports:
            - '80:80'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
            - DB_HOST=
            - DB_NAME=
            - DB_PASS=
            - DB_PORT=
            - DB_SSL_MODE=
            - DB_TABLE_PREFIX=xlist
            - DB_TYPE=
            - DB_USER=
        container_name: alist
        image: 'xhofe/alist:latest'
